packages:
  - apps/*
  - packages/*

catalogs:
  react:
    '@types/react': ^18.3.23
    '@types/react-dom': ^18
    react: ^18.3.1
    react-dom: ^18.3.1
  rspack:
    '@rsbuild/core': ~1.4.15
    '@rsbuild/plugin-less': ^1.4.0
    '@rsbuild/plugin-react': ^1.3.5
    '@rslib/core': ~0.11.2
  storybook:
    '@storybook/addon-docs': ^8.6.14
    '@storybook/addon-essentials': ^8.6.14
    '@storybook/addon-interactions': ^8.6.14
    '@storybook/addon-links': ^8.6.14
    '@storybook/addon-onboarding': ^8.6.14
    '@storybook/blocks': ^8.6.14
    '@storybook/react': ^8.6.14
    '@storybook/test': ^8.6.14
    storybook: ^8.6.14
    storybook-addon-rslib: ^1.0.2
    storybook-react-rsbuild: ^1.0.2
  test:
    '@testing-library/jest-dom': ^6.6.4
    '@testing-library/react': ^16.3.0
    jsdom: ^26.1.0
    vitest: ^3.2.4
  typescript:
    '@types/node': ^22.17.1
    typescript: ~5.9.2
